#!/usr/bin/env bash
# Setup script for Forge walkthrough test repo.
# Creates an isolated test workspace with hermetic Forge, Claude, and Codex settings homes.
#
# Usage:
#   setup-test-repo.sh           # Create test repo (default location)
#   setup-test-repo.sh --reset   # Reset existing repo to clean baseline
#
# Environment:
#   FORGE_TEST_REPO  Override test repo location (default: ~/.forge/manual-testing/walkthrough/test-repo)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

FORGE_TEST_REPO="${FORGE_TEST_REPO:-${FORGE_HOME:-$HOME/.forge}/manual-testing/walkthrough/test-repo}"
# Resolve to absolute path (and expand leading "~"), even if parent dirs don't exist yet.
FORGE_TEST_REPO="$(python3 -c 'import os,sys; print(os.path.abspath(os.path.expanduser(sys.argv[1])))' "$FORGE_TEST_REPO")"

MARKER_FILE="$FORGE_TEST_REPO/.forge-walkthrough-marker"

# --- Safety: refuse known-bad paths ---
check_safe_path() {
    local resolved
    resolved="$(realpath "$1" 2>/dev/null || echo "$1")"

    local -a denylist=("/" "$HOME" "/Users" "/tmp" "/var" "/etc" "/opt" "/usr")
    for bad in "${denylist[@]}"; do
        if [ "$resolved" = "$bad" ] || [ "$resolved" = "$(realpath "$bad" 2>/dev/null || echo "$bad")" ]; then
            echo "ERROR: Refusing to operate on '$resolved' (denylisted path)" >&2
            exit 1
        fi
    done
}

check_safe_path "$FORGE_TEST_REPO"

# --- Generate env.sh (defined early, used by both --reset and fresh init) ---
generate_env() {
    mkdir -p "$FORGE_TEST_REPO/.forge/walkthrough" "$FORGE_TEST_REPO/.claude-user" "$FORGE_TEST_REPO/.codex-user"
    cat > "$FORGE_TEST_REPO/.forge/walkthrough/env.sh" << ENVEOF
# Generated by setup-test-repo.sh -- sandbox Forge state plus Claude/Codex settings.
# HOME stays real (Claude auth, native install, shell config all work).
export FORGE_TEST_REPO="$FORGE_TEST_REPO"
export FORGE_HOME="$FORGE_TEST_REPO/.forge-home"
export CLAUDE_HOME="$FORGE_TEST_REPO/.claude-user"
export CODEX_HOME="$FORGE_TEST_REPO/.codex-user"
export FORGE_DEBUG="1"
echo "Forge walkthrough sandbox active:" >&2
echo "  FORGE_HOME = \$FORGE_HOME (isolated)" >&2
echo "  CLAUDE_HOME = \$CLAUDE_HOME (isolated)" >&2
echo "  CODEX_HOME = \$CODEX_HOME (isolated)" >&2
echo "  HOME       = \$HOME (unchanged)" >&2
echo "  FORGE_DEBUG = \$FORGE_DEBUG (sandbox debug logging)" >&2
ENVEOF
}

# --- Remove walkthrough-derived state that should not persist across reruns ---
scrub_volatile_state() {
    rm -rf "$FORGE_TEST_REPO/.forge/artifacts"
    rm -rf "$FORGE_TEST_REPO/.forge/search-index"
    rm -rf "$FORGE_TEST_REPO/.forge-home/logs"
}

# --- Handle --reset ---
if [ "${1:-}" = "--reset" ]; then
    if [ -d "$FORGE_TEST_REPO" ] && [ -f "$MARKER_FILE" ]; then
        # Marker exists: fast reset via git
        if [ ! -f "$FORGE_TEST_REPO/src/main.py" ] || [ ! -f "$FORGE_TEST_REPO/CLAUDE.md" ]; then
            echo "ERROR: Expected structure not found (src/main.py, CLAUDE.md)." >&2
            echo "This does not look like a forge-walkthrough repo. Refusing --reset." >&2
            exit 1
        fi
        echo "Resetting test repo: $FORGE_TEST_REPO" >&2
        cd "$FORGE_TEST_REPO"
        git clean -fdx -e .forge/walkthrough/ -e .forge-home/
        git checkout -- .
        mkdir -p .forge-home
        mkdir -p .forge/walkthrough
        scrub_volatile_state
        echo "forge-walkthrough-marker" > "$MARKER_FILE"
        generate_env
        echo "Reset complete." >&2
        exit 0
    elif [ -d "$FORGE_TEST_REPO" ]; then
        # No marker but dir exists: nuke and fall through to fresh init
        echo "No marker file found. Removing stale directory and recreating." >&2
        rm -rf "$FORGE_TEST_REPO"
    fi
    # Fall through to fresh init below
fi

# --- Idempotent: skip if already exists ---
if [ -d "$FORGE_TEST_REPO" ] && [ -f "$MARKER_FILE" ]; then
    # Keep the repo baseline, but scrub walkthrough-derived artifacts so reruns start clean.
    scrub_volatile_state
    # Ensure env.sh exists and stays up to date (e.g., if skill path moved).
    generate_env
    echo "Test repo already exists: $FORGE_TEST_REPO" >&2
    echo "Scrubbed volatile walkthrough state (.forge/artifacts, .forge/search-index, .forge-home/logs)." >&2
    echo "Env file: $FORGE_TEST_REPO/.forge/walkthrough/env.sh" >&2
    echo "Use --reset to clean and re-initialize." >&2
    exit 0
fi

# --- Refuse to init into an existing directory without a marker ---
if [ -d "$FORGE_TEST_REPO" ] && [ ! -f "$MARKER_FILE" ]; then
    echo "ERROR: Directory exists but has no marker: $FORGE_TEST_REPO" >&2
    echo "This was not created by setup-test-repo.sh. Refusing to initialize." >&2
    echo "Remove it manually or choose a different FORGE_TEST_REPO path." >&2
    exit 1
fi

# --- Fresh init ---
echo "Creating test repo: $FORGE_TEST_REPO" >&2

mkdir -p "$FORGE_TEST_REPO"
cd "$FORGE_TEST_REPO"

# Isolated Forge state and user-scoped Claude extension settings (HOME stays real)
mkdir -p .forge-home .claude-user .codex-user

# State/reports namespace
mkdir -p .forge/walkthrough

# Source tree
mkdir -p src tests .claude

# --- Write fixture files ---

cat > src/main.py << 'PYEOF'
def hello():
    return "world"
PYEOF

cat > tests/test_main.py << 'PYEOF'
from src.main import hello


def test_hello():
    assert hello() == "world"
PYEOF

cat > CLAUDE.md << 'PYEOF'
# forge-walkthrough

This is a test repo for the Forge walkthrough skill.
PYEOF

cat > README.md << 'PYEOF'
# forge-walkthrough

Test workspace for the Forge `/walkthrough` skill.
PYEOF

cat > .claude/settings.local.json << 'JSONEOF'
{
  "permissions": {
    "allow": [
      "Bash(npm test)",
      "Bash(uv run pytest*)"
    ]
  },
  "env": {
    "MY_CUSTOM_VAR": "should-survive-forge"
  }
}
JSONEOF

cat > .gitignore << 'GITEOF'
.DS_Store
.idea/
.env
.forge-home/
.claude-user/
.codex-user/
.forge/
__pycache__/
*.pyc
GITEOF

# --- Git init ---
git init -q
git config user.email "forge-test@localhost"
git config user.name "Forge Test"
git config commit.gpgsign false
git add -A
# Force-add paths excluded by Claude Code's global gitignore (~/.config/git/ignore):
#   **/.claude/settings.local.json, **/CLAUDE.local.md
for f in .claude/ CLAUDE.local.md; do
    [ -e "$f" ] && git add -f "$f"
done
git commit -q -m "Initial test repo for forge walkthrough"

# --- Write marker (after commit so it's untracked = survives git checkout) ---
echo "forge-walkthrough-marker" > "$MARKER_FILE"

# --- Generate env.sh ---
generate_env

echo "Test repo created: $FORGE_TEST_REPO" >&2
echo "FORGE_HOME: $FORGE_TEST_REPO/.forge-home/" >&2
echo "CLAUDE_HOME: $FORGE_TEST_REPO/.claude-user/" >&2
echo "CODEX_HOME: $FORGE_TEST_REPO/.codex-user/" >&2
echo "Env file: $FORGE_TEST_REPO/.forge/walkthrough/env.sh" >&2
