"""Regression test for QA issue 6: __pycache__/.pyc files installed in Docker.

Root cause: The installer's plan() used _get_git_tracked_files() to filter
build artifacts, but inside Docker the .git/ directory is excluded by
.dockerignore. With git unavailable, the fallback accepted ALL files from
rglob("*"), including __pycache__/*.pyc generated by uv sync at build time.

Fix: Added _is_installable() that unconditionally rejects __pycache__
directories and .pyc/.pyo extensions, independent of git availability.

Affected file: src/forge/install/installer.py
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytestmark = pytest.mark.regression


class TestIsInstallable:
    """_is_installable rejects build artifacts regardless of git availability."""

    def test_rejects_pyc_file(self) -> None:
        from forge.install.installer import _is_installable

        assert not _is_installable(Path("skills/qa/__pycache__/SKILL.cpython-312.pyc"))

    def test_rejects_pyo_file(self) -> None:
        from forge.install.installer import _is_installable

        assert not _is_installable(Path("skills/qa/module.pyo"))

    def test_rejects_pycache_directory(self) -> None:
        from forge.install.installer import _is_installable

        assert not _is_installable(Path("skills/qa/__pycache__/anything.txt"))

    def test_rejects_dotfiles(self) -> None:
        from forge.install.installer import _is_installable

        assert not _is_installable(Path("skills/qa/.hidden"))

    def test_rejects_pytest_cache(self) -> None:
        from forge.install.installer import _is_installable

        assert not _is_installable(Path("skills/.pytest_cache/v/cache/nodeids"))

    def test_accepts_normal_file(self) -> None:
        from forge.install.installer import _is_installable

        assert _is_installable(Path("skills/qa/SKILL.md"))

    def test_accepts_python_source(self) -> None:
        from forge.install.installer import _is_installable

        assert _is_installable(Path("skills/qa/scripts/walkthrough-state.py"))

    def test_accepts_shell_script(self) -> None:
        from forge.install.installer import _is_installable

        assert _is_installable(Path("skills/qa/scripts/start-container.sh"))


class TestPlanExcludesPycacheWithoutGit:
    """Installer.plan() excludes __pycache__ even when git is unavailable."""

    def test_pycache_excluded_when_git_unavailable(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        """Simulate Docker environment: source tree has __pycache__ but no .git/."""
        from forge.install.installer import Installer, get_extensions_root
        from forge.install.models import (
            InstallMode,
            InstallModule,
            InstallProfile,
            InstallScope,
        )

        # Create a minimal skill source with __pycache__ contamination
        source_root = get_extensions_root()
        skill_dir = source_root / "skills" / "test-pycache-regression"
        pycache_dir = skill_dir / "__pycache__"
        pycache_dir.mkdir(parents=True, exist_ok=True)

        (skill_dir / "SKILL.md").write_text("""\
---
name: forge:test-pycache-regression
description: Temporary package for the pycache exclusion regression.
---

# Test skill
""")
        (pycache_dir / "SKILL.cpython-312.pyc").write_bytes(b"\x00\x00\x00\x00")

        try:
            # Force git to be unavailable (simulates Docker without .git/)
            monkeypatch.setattr(
                "forge.install.installer._get_git_tracked_files",
                lambda _: None,
            )

            installer = Installer(
                scope=InstallScope.USER,
                project_root=None,
            )
            plan = installer.plan(
                profile=InstallProfile.STANDARD,
                mode=InstallMode.COPY,
                _modules_override={InstallModule.SKILLS},
            )

            planned_targets = [fp.target_path for fp in plan.files]
            # The .pyc file must NOT appear in the plan
            assert not any(".pyc" in t for t in planned_targets), (
                f"__pycache__/.pyc files leaked into install plan: " f"{[t for t in planned_targets if '.pyc' in t]}"
            )
            # The SKILL.md SHOULD appear
            assert any("test-pycache-regression" in t and "SKILL.md" in t for t in planned_targets)
        finally:
            # Clean up test fixture from source tree
            import shutil

            shutil.rmtree(skill_dir, ignore_errors=True)
